# Generated by Django 5.1.1 on 2024-10-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_requests', '0002_rejectedfriendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=10),
        ),
    ]
